# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadImages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_comment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='UploadImages.User'),
            preserve_default=False,
        ),
    ]
